---
abstract: 'Perl interface to USB Test & Measurement (USBTMC) backend.'
author:
  - 'Simon Reinhardt <simon.reinhardt@stud.uni-regensburg.de>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.008, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: USB-TMC
requires:
  Carp: '0'
  Data::Dumper: '0'
  Moose: '0'
  MooseX::Params::Validate: '0'
  USB::LibUSB: '0'
  constant: '0'
  strict: '0'
  warnings: '0'
resources:
  IRC: "'irc://chat.freenode.net/#labmeasurement'"
  MailingList: "'https://www-mailman.uni-regensburg.de/mailman/listinfo/lab-measurement-users'"
  bugtracker: https://github.com/lab-measurement/USB-TMC/issues
  homepage: http://www.labmeasurement.de/
  repository: https://github.com/lab-measurement/USB-TMC.git
version: '0.006'
x_serialization_backend: 'YAML::Tiny version 1.69'
